"""0001_initial_schema

Revision ID: c885a98c1195
Revises: 
Create Date: 2026-10-07 10:00:29.100460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c885a98c1195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_family', sa.String(length=32), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_records_id'), ['id'], unique=False)

    op.create_table('federated_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('selected_hospital_ids', sa.JSON(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('global_train_loss', sa.Float(), nullable=True),
    sa.Column('global_train_acc', sa.Float(), nullable=True),
    sa.Column('global_val_loss', sa.Float(), nullable=True),
    sa.Column('global_val_acc', sa.Float(), nullable=True),
    sa.Column('global_val_f1', sa.Float(), nullable=True),
    sa.Column('global_val_precision', sa.Float(), nullable=True),
    sa.Column('global_val_recall', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('federated_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federated_rounds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_federated_rounds_round_number'), ['round_number'], unique=True)

    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('class_distribution', sa.JSON(), nullable=True),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('dataset_split_counts', sa.JSON(), nullable=True),
    sa.Column('dataset_is_valid', sa.Boolean(), nullable=True),
    sa.Column('dataset_updated_at', sa.DateTime(), nullable=True),
    sa.Column('dataset_validated_at', sa.DateTime(), nullable=True),
    sa.Column('current_model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_hospital_code'), ['hospital_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_id'), ['id'], unique=False)

    op.create_table('hospital_training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_code', sa.String(length=32), nullable=False),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('train_acc', sa.Float(), nullable=True),
    sa.Column('train_f1', sa.Float(), nullable=True),
    sa.Column('val_loss', sa.Float(), nullable=True),
    sa.Column('val_acc', sa.Float(), nullable=True),
    sa.Column('val_f1', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['federated_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_training_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_training_runs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_training_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_training_runs_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_training_runs_round_number'), ['round_number'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_family', sa.String(length=32), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('mcc', sa.Float(), nullable=True),
    sa.Column('is_deployed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('gate_report', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('previous_deployed_version_id', sa.Integer(), nullable=True),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['previous_deployed_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['federated_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_version_tag'), ['version_tag'], unique=True)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('admitted_date', sa.String(length=32), nullable=True),
    sa.Column('last_inspected_date', sa.String(length=32), nullable=True),
    sa.Column('urine_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('hospital_update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_update_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_update_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_update_logs_id'), ['id'], unique=False)

    op.create_table('inference_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=True),
    sa.Column('result_label', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inference_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_logs_model_version_id'), ['model_version_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('result_label', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('explainability_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_hospital_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('inference_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_logs_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_inference_logs_id'))
        batch_op.drop_index(batch_op.f('ix_inference_logs_hospital_id'))

    op.drop_table('inference_logs')
    with op.batch_alter_table('hospital_update_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_update_logs_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_update_logs_hospital_id'))

    op.drop_table('hospital_update_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_hospital_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_id'))
        batch_op.drop_index(batch_op.f('ix_system_logs_hospital_id'))

    op.drop_table('system_logs')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.drop_index(batch_op.f('ix_patients_hospital_id'))

    op.drop_table('patients')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_version_tag'))
        batch_op.drop_index(batch_op.f('ix_model_versions_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('hospital_training_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_training_runs_round_number'))
        batch_op.drop_index(batch_op.f('ix_hospital_training_runs_round_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_training_runs_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_training_runs_hospital_id'))

    op.drop_table('hospital_training_runs')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_id'))
        batch_op.drop_index(batch_op.f('ix_hospitals_hospital_code'))

    op.drop_table('hospitals')
    with op.batch_alter_table('federated_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federated_rounds_round_number'))
        batch_op.drop_index(batch_op.f('ix_federated_rounds_id'))

    op.drop_table('federated_rounds')
    with op.batch_alter_table('drift_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_records_id'))

    op.drop_table('drift_records')
    # ### end Alembic commands ###
